### reg 
POST https://localhost:8080/api/reg
content-type: application/json

{
    "name": "pekka",
    "password": "password",
    "email": "temp@email.com",
    "username": "user2"
}

### login 
POST https://localhost:8080/api/login
content-type: application/json

{
    "username": "user2",
    "password": "password"
}
### add new club
Post https://localhost:8080/api/auth/club/new
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcxMDAxOTc1MiwiZXhwIjoxNzEwMDQ4NTUyfQ.QkUiWgxOkSWjdQD8uzl1pgPD5fLQUZdMvm10sVm020w
content-type: application/json

{
    "clubName": "SeuraajienSeura"
}

### join
post https://localhost:8080/api/auth/club/join
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcxMDAxOTc1MiwiZXhwIjoxNzEwMDQ4NTUyfQ.QkUiWgxOkSWjdQD8uzl1pgPD5fLQUZdMvm10sVm020w
content-type: application/json

{
    "clubName": "SeuraajienSeura"

}



### add new copm
Post https://localhost:8080/api/auth/competition/new
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcxMDAxOTc1MiwiZXhwIjoxNzEwMDQ4NTUyfQ.QkUiWgxOkSWjdQD8uzl1pgPD5fLQUZdMvm10sVm020w
content-type: application/json

{
    "competitionName": "nopean-laukauksen-mestaruus",
    "competitionType": "rifle"
}

### add new team
Post https://localhost:8080/api/competition/team/new
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcxMDAxOTc1MiwiZXhwIjoxNzEwMDQ4NTUyfQ.QkUiWgxOkSWjdQD8uzl1pgPD5fLQUZdMvm10sVm020w
content-type: application/json

{
    "competitionName": "nopean-laukauksen-mestaruus"
}

###  join team
Post https://localhost:8080/api/competition/team/member/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcxMDAxOTc1MiwiZXhwIjoxNzEwMDQ4NTUyfQ.QkUiWgxOkSWjdQD8uzl1pgPD5fLQUZdMvm10sVm020w
content-type: application/json

{
    "competitionName": "nopean-laukauksen-mestaruus"
}

### add score
Post https://localhost:8080/api/competition/team/member/score/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcxMDAxOTc1MiwiZXhwIjoxNzEwMDQ4NTUyfQ.QkUiWgxOkSWjdQD8uzl1pgPD5fLQUZdMvm10sVm020w
content-type: application/json

{
    "competitionName": "nopean-laukauksen-mestaruus",
    "scoreList":[0.1 ,3,6,1]
}


### search competitions

GET https://localhost:8080/api/competition/query?search=&page=0&size=10

### get comp by ID
GET https://localhost:8080/api/competition/result/kilpa
