### reg test 1
POST http://localhost:8080/api/reg
content-type: application/json

{
    "name": "Username",
    "password": "password",
    "email": "temp@email.com",
    "roles": "ROLE_USER"
}

### log test 1 - correct password
POST http://localhost:8080/api/login
content-type: application/json

{
    "username": "Username",
    "password": "password"
}
### 3
GET http://localhost:8080/api/auth/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJVc2VybmFtZSIsImlhdCI6MTcwNzYxMjA5NSwiZXhwIjoxNzA3NjQwODk1fQ.RdVJ7mngL1TiKTV4gw3lKrw_vKNEbHCLf_3z6wMHIrChw-q96WaajMrpWBFp7jWwOEzoEwqS9udHkyx-lQqstQ
